// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tubnexxquemvtrsuxeqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1Ym5leHhxdWVtdnRyc3V4ZXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3Njc2MTAsImV4cCI6MjA3MzM0MzYxMH0.Kl3JgSFHekdv6FSVIl4lnJZW975aw6NahkOcb76CmAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});